### ISSUE TITLE
`formaction="tax_delete"` runs into 404 Not found error

### ISSUE THREAD

**Issue by simonsymhoven** [begicf/areport#2]
If you delete a taxonomy, a 404 error page dissapears. Is this a expected behaviour because there is no functionality impleted for or is it a bug?

**Comment by simonsymhoven** [comment]
`<button formaction="tax_delete" class="btn btn-outline-danger">`

I think the `formaction`  is wrong and should be `/taxonomy/delete`?

**Comment by simonsymhoven** [comment]
fixed in #3

**Comment by begicf** [comment]
Merged.
